version: "3.9"

networks:
  aide1:
    driver: bridge

services:
  postgres:
    image: postgres:15
    container_name: mlflow-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - aide1

  minio:
    image: minio/minio
    container_name: mlflow-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - aide1

  mlflow:
    build:
      context: ./services/mlflow
    container_name: mlflow-server
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    command: >
      mlflow server
      --backend-store-uri postgresql://${MLFLOW_SQL_USER}:${MLFLOW_SQL_PASSWORD}@${MLFLOW_SQL_HOST}:${MLFLOW_SQL_PORT}/${MLFLOW_SQL_DATABASE}
      --default-artifact-root gs://${MLFLOW_OBJECT_STORAGE_BUCKET}/
      --host 0.0.0.0
      --port 5000
      --allowed-hosts "*"
    ports:
      - "5000:5000"
    networks:
      - aide1

  api:
    build:
      dockerfile: ./services/api/Dockerfile
      tags:
        - bird-classification-api:latest
    container_name: bird-api
    volumes:
      - type: bind
        source: ./services/api
        target: /app/services/api
    environment:
      HTTP_PORT: ${HTTP_PORT}
      WORKERS: ${WORKERS}
      KSERVE_MODEL_URL: ${KSERVE_MODEL_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8000:8000"
    networks:
      - aide1

volumes:
  postgres_data:
  minio_data:
