import axios from 'axios';

const CHATBOT_API_URL =
  (window.__ENV__ && window.__ENV__.REACT_APP_CHATBOT_API_URL) ||
  process.env.REACT_APP_CHATBOT_API_URL ||
  'http://localhost:8000';
const AUTH_API_URL =
  (window.__ENV__ && window.__ENV__.REACT_APP_AUTH_API_URL) ||
  process.env.REACT_APP_AUTH_API_URL ||
  'http://localhost:8001';
const API_TIMEOUT = 30000;

const authApi = axios.create({
  baseURL: AUTH_API_URL,
  timeout: API_TIMEOUT,
});

const chatbotApi = axios.create({
  baseURL: CHATBOT_API_URL,
  timeout: API_TIMEOUT,
});

export const registerUser = async (email, password, fullName) => {
  const response = await authApi.post('/register', {
    email,
    password,
    full_name: fullName,
  });
  return response.data;
};

export const loginUser = async (email, password) => {
  const response = await authApi.post('/login', { email, password });
  return response.data;
};

/**
 * Stream a chat query to the chatbot service.
 * @param {string} query
 * @param {string|null} imgB64
 * @param {function} onChunk - called with each text chunk as it arrives
 * @param {number|null} userId
 * @param {string|null} conversationId - UUID generated by the client
 */
export const sendChatQuery = async (query, imgB64 = null, onChunk, userId = null, conversationId = null) => {
  const payload = { query };
  if (imgB64) payload.img_b64 = imgB64;
  if (userId) payload.user_id = userId;
  if (conversationId) payload.conversation_id = conversationId;

  const response = await fetch(`${CHATBOT_API_URL}/chat`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(text || `HTTP ${response.status}`);
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = '';

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;

    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split('\n');
    buffer = lines.pop();

    for (const line of lines) {
      if (!line.startsWith('data:')) continue;
      const data = line.startsWith('data: ') ? line.slice(6) : line.slice(5);
      if (data === '[DONE]') return;
      if (data.startsWith('[ERROR]')) throw new Error(data.slice(7).trim());
      if (data) onChunk(data.replace(/\\n/g, '\n'));
    }
  }
};

/**
 * Check the health of the chatbot service
 * @returns {Promise} - The health status
 */
export const checkChatbotHealth = async () => {
  try {
    const response = await chatbotApi.get('/health');
    return response.data;
  } catch (error) {
    console.error('Chatbot health check failed:', error);
    throw error;
  }
};

export { chatbotApi };
