modelName: birds-model

autoscaling:
  minReplicas: 0
  maxReplicas: 5
  scaleTarget: 10
  scaleToZeroPodRetentionPeriod: "300s"

resources:
  limits:
    cpu: "2000m"
    memory: "6Gi"
  requests:
    cpu: "1000m"
    memory: "4Gi"

serviceAccount:
  name: kserve-sa
  gcpServiceAccount: kserve-sa@project-2a55a756-9eba-4a36-8c6.iam.gserviceaccount.com
  gcpProject: project-2a55a756-9eba-4a36-8c6

predictor:
  storageUri: "gs://model_aide/bird_classification/v1"
