query_enricher:
  model: "gpt-4.1"
  temperature: 0.0
  top_p: 1.0
  n: 1
  frequency_penalty: 0.0
  max_completion_tokens: 1024

answer_generator:
  model: "gpt-4.1"
  temperature: 0.0
  top_p: 1.0
  n: 1
  frequency_penalty: 0.0
  max_completion_tokens: 8192

litellm:
  model: "gpt-4.1"
  temperature: 0.0
  top_p: 1.0
  n: 1
  frequency_penalty: 0.0
  max_completion_tokens: 8192
  dimension: 1536
  embedding_model: "text-embedding-3-large"