apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempo
  namespace: {{ .Values.namespace }}
  labels:
    app: tempo
spec:
  replicas: {{ .Values.tempo.replicas }}
  selector:
    matchLabels:
      app: tempo
  serviceName: tempo-headless
  template:
    metadata:
      labels:
        app: tempo
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: tempo
          image: {{ .Values.tempo.image }}
          args:
            - -config.file=/etc/tempo/tempo.yaml
          ports:
            - name: http
              containerPort: {{ .Values.tempo.httpPort }}
            - name: grpc
              containerPort: {{ .Values.tempo.grpcPort }}
            - name: otlp-grpc
              containerPort: {{ .Values.tempo.otlpGrpcPort }}
            - name: otlp-http
              containerPort: {{ .Values.tempo.otlpHttpPort }}
          volumeMounts:
            - name: config
              mountPath: /etc/tempo
            - name: data
              mountPath: {{ .Values.storage.path }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 45
            periodSeconds: 30
          resources:
            {{- toYaml .Values.tempo.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: tempo-config
  {{- if .Values.storage.persistentVolume.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.storage.persistentVolume.size }}
  {{- else }}
      volumes:
        - name: data
          emptyDir: {}
  {{- end }}
