steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/$_MLFLOW_REPO/mlflow:$_TAG_NAME',
      '-f', 'Dockerfile',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/$_MLFLOW_REPO/mlflow:$_TAG_NAME'
    ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/$_MLFLOW_REPO/mlflow:$_TAG_NAME'

options:
  logging: CLOUD_LOGGING_ONLY
