apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: {{ .Values.namespace }}
  labels:
    app: tempo
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
    - name: otlp-grpc
      port: {{ .Values.service.otlpGrpcPort }}
      targetPort: otlp-grpc
    - name: otlp-http
      port: {{ .Values.service.otlpHttpPort }}
      targetPort: otlp-http
  selector:
    app: tempo
