[project]
name = "chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vuniem131104", email = "niemhoalongvu@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "langgraph>=1.1.6",
    "fastapi>=0.100.0",
    "uvicorn>=0.24.0",
    "pydantic>=2.0.0",
    "pydantic-settings>=2.0.0",
    "httpx>=0.25.0",
    "structlog>=23.0.0",
    "spicy>=0.16.0",
    "database",
    "aiokafka>=0.11.0",
]

[project.scripts]
chatbot = "chatbot:main"

[tool.uv.sources]
database = { workspace = true }

[build-system]
requires = ["uv_build>=0.9.4,<0.10.0"]
build-backend = "uv_build"
